import api from "./api";
export const getOverview = () => api.get("/reports/overview");
export const getEventsByMonth = (y) => api.get(`/reports/events-by-month?year=${y || ''}`);
export const getAttendeeReport = () => api.get("/reports/attendees");
export const getAttendeeDetail = () => api.get("/reports/attendees-detail");
export const getBudgetReport = () => api.get("/reports/budget");
export const getTaskStats = () => api.get("/reports/tasks");
export const getTaskDetail = () => api.get("/reports/tasks-detail");
export const getEventsByType = () => api.get("/reports/events-by-type");
export const getFeedbackStats = () => api.get("/reports/feedbacks");
export const getFeedbackDetail = () => api.get("/reports/feedbacks-detail");
